services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_HOST: ${DB_HOST}
    volumes:
      - database_dockerizing:/var/lib/postgresql/data
     # - ./dbshell:/docker-entrypoint-initdb.d/
    networks:
      - fullstack
  api:
    container_name: backend
    build: .
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
    ports:
      - 3000:5000
    restart: always
    volumes:
      - api_volume:/usr/src/app/
    depends_on:
      - postgres
    networks:
      - fullstack

volumes:
  database_dockerizing:
  api_volume:

networks:
  fullstack:
    driver: bridge