name: Push to github
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Echo a message
        run: echo "🎉 The workflow was triggered by a push!"